version: 2
jobs:
  build:
    working_directory: ~/size-of-npm
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: "Install"
          command: cd size; npx npm-check-updates -u; yarn
      - run:
          name: "Sizing"
          command: cd size; ./size.sh
      - run:
          name: "JSON conversion"
          command: cd size; node tojson.js
      - add_ssh_keys:
          fingerprints:
            - "f4:d1:e9:19:33:98:33:e1:c5:47:5d:e7:21:e6:16:c3"
      - run:
          name: "Git commit + push"
          command: cd size; ./push.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "00 20 * * *" # every day at 20:00 UTC
          filters:
            branches:
              only: master

    jobs:
      - build
