version: 2
jobs:
  build:
    working_directory: ~/size-of-npm/size
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: "Install"
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: "Sizing"
          command: ./size.sh
      - run:
          name: "JSON conversion"
          command: node tojson.js
      - add_ssh_keys:
          fingerprints:
            - "f4:d1:e9:19:33:98:33:e1:c5:47:5d:e7:21:e6:16:c3"
      - run:
          name: "Git commit + push"
          command: ./push.sh
